# Generated by Django 4.1 on 2022-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hechizos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
