# Generated by Django 4.1 on 2022-09-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCasa', '0004_category_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
