# Generated by Django 4.1 on 2022-09-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCasa', '0008_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=60),
        ),
    ]
