# Generated by Django 4.1 on 2022-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCasa', '0010_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
    ]
